# Generated by Django 5.0.7 on 2025-10-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('base_dn', models.CharField(max_length=255)),
                ('bind_user', models.CharField(max_length=255)),
                ('bind_password_encrypted', models.TextField()),
                ('group_search', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=465)),
                ('username', models.CharField(max_length=255)),
                ('password_encrypted', models.TextField()),
                ('use_ssl', models.BooleanField(default=True)),
                ('use_tls', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SslConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_file', models.FileField(upload_to='ssl_certs/')),
                ('key_file', models.FileField(upload_to='ssl_keys/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
