# Generated by Django 5.0.7 on 2025-10-28 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ldapconfig',
            options={'verbose_name': 'LDAP Config (Legado)', 'verbose_name_plural': 'LDAP Configs (Legado)'},
        ),
        migrations.AlterModelOptions(
            name='smtpconfig',
            options={'verbose_name': 'SMTP Config (Legado)', 'verbose_name_plural': 'SMTP Configs (Legado)'},
        ),
        migrations.AlterModelOptions(
            name='sslconfig',
            options={'verbose_name': 'Configuração SSL', 'verbose_name_plural': 'Configurações SSL'},
        ),
        migrations.CreateModel(
            name='LdapDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('BR', '🇧🇷 Brasil'), ('AR', '🇦🇷 Argentina'), ('MX', '🇲🇽 México'), ('DE', '🇩🇪 Alemanha'), ('IT', '🇮🇹 Itália'), ('CN', '🇨🇳 China'), ('US', '🇺🇸 Estados Unidos')], max_length=5, unique=True, verbose_name='País')),
                ('name', models.CharField(help_text='Ex: Active Directory - Brasil', max_length=100, verbose_name='Nome da Configuração')),
                ('ldap_server', models.CharField(help_text='Ex: ldap://S28BRDC2-16.BR.ILPEAORG.COM ou S28BRDC2-16.BR.ILPEAORG.COM', max_length=200, verbose_name='Servidor LDAP')),
                ('port', models.IntegerField(default=389, help_text='389 para LDAP padrão, 636 para LDAPS (SSL)', verbose_name='Porta')),
                ('base_dn', models.CharField(help_text='Ex: DC=BR,DC=ILPEAORG,DC=COM', max_length=300, verbose_name='Base DN')),
                ('bind_user_dn', models.CharField(help_text='Ex: CN=Admin,CN=Users,DC=BR,DC=ILPEAORG,DC=COM', max_length=300, verbose_name='User DN para Bind')),
                ('bind_password_encrypted', models.TextField(verbose_name='Senha de Bind (Criptografada)')),
                ('user_search_base', models.CharField(blank=True, help_text='Deixe vazio para usar Base DN', max_length=300, verbose_name='Base de Busca de Usuários')),
                ('search_filter', models.CharField(default='(sAMAccountName={username})', help_text='Use {username} como placeholder', max_length=200, verbose_name='Filtro de Busca LDAP')),
                ('attr_first_name', models.CharField(default='givenName', max_length=50, verbose_name='Atributo: Primeiro Nome')),
                ('attr_last_name', models.CharField(default='sn', max_length=50, verbose_name='Atributo: Sobrenome')),
                ('attr_email', models.CharField(default='mail', max_length=50, verbose_name='Atributo: E-mail')),
                ('use_ssl', models.BooleanField(default=False, help_text='Conexão segura na porta 636', verbose_name='Usar SSL (LDAPS)')),
                ('use_tls', models.BooleanField(default=False, help_text='Iniciar TLS após conexão (porta 389)', verbose_name='Usar START_TLS')),
                ('is_active', models.BooleanField(default=True, help_text='Desative para impedir autenticações neste país', verbose_name='Ativo')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Último Teste de Conexão')),
                ('last_test_status', models.BooleanField(default=False, verbose_name='Status do Último Teste')),
                ('last_test_message', models.TextField(blank=True, verbose_name='Mensagem do Último Teste')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldap_directories_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldap_directories_updated', to=settings.AUTH_USER_MODEL, verbose_name='Última atualização por')),
            ],
            options={
                'verbose_name': 'Active Directory',
                'verbose_name_plural': 'Active Directories',
                'db_table': 'adminpanel_ldap_directory',
                'ordering': ['country_code'],
            },
        ),
        migrations.CreateModel(
            name='SmtpConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: SMTP HCL Notes - Brasil', max_length=100, unique=True, verbose_name='Nome da Configuração')),
                ('smtp_server', models.CharField(help_text='Ex: ilpea.smtp001-ce.cloud-y.com', max_length=200, verbose_name='Servidor SMTP')),
                ('smtp_port', models.IntegerField(default=587, help_text='25 (padrão), 465 (SSL), 587 (TLS)', verbose_name='Porta')),
                ('smtp_username', models.CharField(help_text='Ex: signbr@ilpea.com', max_length=200, verbose_name='Usuário SMTP')),
                ('smtp_password_encrypted', models.TextField(verbose_name='Senha SMTP (Criptografada)')),
                ('use_tls', models.BooleanField(default=True, help_text='START_TLS na porta 587', verbose_name='Usar TLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='SSL/TLS direto na porta 465', verbose_name='Usar SSL')),
                ('default_sender', models.EmailField(help_text='E-mail que aparecerá como remetente', max_length=254, verbose_name='Remetente Padrão')),
                ('default_sender_name', models.CharField(default='ILPEA SupplyConnect', max_length=100, verbose_name='Nome do Remetente')),
                ('max_emails', models.IntegerField(default=5, verbose_name='Máximo de E-mails por Conexão')),
                ('timeout', models.IntegerField(default=10, verbose_name='Timeout (segundos)')),
                ('is_active', models.BooleanField(default=True, help_text='Apenas uma configuração pode estar ativa', verbose_name='Ativo')),
                ('last_test_date', models.DateTimeField(blank=True, null=True, verbose_name='Último Teste de Envio')),
                ('last_test_status', models.BooleanField(default=False, verbose_name='Status do Último Teste')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smtp_configurations_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Configuração SMTP',
                'verbose_name_plural': 'Configurações SMTP',
                'db_table': 'adminpanel_smtp_configuration',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
