# Generated by Django 5.0.7 on 2025-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_ldapconfig_options_alter_smtpconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapdirectory',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Se True, esta configuração é gerenciada pelo Admin Global', verbose_name='Configuração Global'),
        ),
        migrations.AddField(
            model_name='smtpconfiguration',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Se True, esta configuração é gerenciada pelo Admin Global', verbose_name='Configuração Global'),
        ),
    ]
