# Generated by Django 5.0.7 on 2025-10-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_ldapdirectory_is_global_smtpconfiguration_is_global'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smtpconfiguration',
            old_name='default_sender',
            new_name='from_email',
        ),
        migrations.RenameField(
            model_name='smtpconfiguration',
            old_name='default_sender_name',
            new_name='from_name',
        ),
        migrations.RenameField(
            model_name='smtpconfiguration',
            old_name='smtp_server',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='smtpconfiguration',
            old_name='smtp_password_encrypted',
            new_name='password_encrypted',
        ),
        migrations.RenameField(
            model_name='smtpconfiguration',
            old_name='smtp_port',
            new_name='port',
        ),
        migrations.RenameField(
            model_name='smtpconfiguration',
            old_name='smtp_username',
            new_name='username',
        ),
    ]
