# Generated by Django 5.0.7 on 2025-10-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='É fornecedor'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('pt-br', 'Português (Brasil)'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano'), ('zh-hans', '中文 (简体)')], default='pt-br', max_length=10, verbose_name='Idioma Preferido'),
        ),
    ]
