# Generated by Django 5.0.7 on 2025-10-28 20:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_supplier_user_preferred_language'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, choices=[('BR', '🇧🇷 Brasil'), ('AR', '🇦🇷 Argentina'), ('MX', '🇲🇽 México'), ('DE', '🇩🇪 Alemanha'), ('IT', '🇮🇹 Itália'), ('CN', '🇨🇳 China'), ('US', '🇺🇸 Estados Unidos')], help_text='País de origem ou responsabilidade (para Country Admin)', max_length=5, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 28, 20, 37, 50, 774749, tzinfo=datetime.timezone.utc), verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_country_admin',
            field=models.BooleanField(default=False, help_text='Pode gerenciar configurações do seu país', verbose_name='Administrador do País'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.companyunit', verbose_name='Unidade da Empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin_local',
            field=models.BooleanField(default=False, verbose_name='Admin Local (Legado)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='Usuário externo (fornecedor/parceiro)', verbose_name='É Fornecedor'),
        ),
    ]
