# Generated by Django 5.0.7 on 2025-10-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_country_code_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ad_groups',
            field=models.TextField(blank=True, help_text='Grupos do Active Directory (JSON)', null=True, verbose_name='Grupos do AD'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ad_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização AD'),
        ),
    ]
