# Generated by Django 5.0.7 on 2025-11-03 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('BR', '🇧🇷 Brasil'), ('AR', '🇦🇷 Argentina'), ('MX', '🇲🇽 México'), ('DE', '🇩🇪 Alemanha'), ('IT', '🇮🇹 Itália'), ('CN', '🇨🇳 China'), ('US', '🇺🇸 Estados Unidos'), ('ES', '🇪🇸 Espanha'), ('FR', '🇫🇷 França'), ('GB', '🇬🇧 Reino Unido'), ('JP', '🇯🇵 Japão'), ('IN', '🇮🇳 Índia'), ('CA', '🇨🇦 Canadá'), ('AU', '🇦🇺 Austrália'), ('CL', '🇨🇱 Chile'), ('CO', '🇨🇴 Colômbia'), ('PE', '🇵🇪 Peru'), ('UY', '🇺🇾 Uruguai'), ('PY', '🇵🇾 Paraguai'), ('PT', '🇵🇹 Portugal'), ('NL', '🇳🇱 Holanda'), ('BE', '🇧🇪 Bélgica'), ('CH', '🇨🇭 Suíça'), ('AT', '🇦🇹 Áustria'), ('PL', '🇵🇱 Polônia'), ('CZ', '🇨🇿 República Tcheca'), ('RU', '🇷🇺 Rússia'), ('ZA', '🇿🇦 África do Sul'), ('EG', '🇪🇬 Egito'), ('KR', '🇰🇷 Coreia do Sul'), ('TH', '🇹🇭 Tailândia'), ('VN', '🇻🇳 Vietnã'), ('ID', '🇮🇩 Indonésia'), ('MY', '🇲🇾 Malásia'), ('SG', '🇸🇬 Singapura'), ('TR', '🇹🇷 Turquia'), ('SA', '🇸🇦 Arábia Saudita'), ('AE', '🇦🇪 Emirados Árabes')], max_length=2)),
                ('name', models.CharField(default='', max_length=200)),
                ('distinguished_name', models.CharField(default='', max_length=500, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('member_count', models.IntegerField(default=0)),
                ('can_create_suppliers', models.BooleanField(default=False, verbose_name='Pode criar fornecedores')),
                ('can_edit_suppliers', models.BooleanField(default=False, verbose_name='Pode editar fornecedores')),
                ('can_delete_suppliers', models.BooleanField(default=False, verbose_name='Pode excluir fornecedores')),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo do AD',
                'verbose_name_plural': 'Grupos do AD',
                'ordering': ['country_code', 'name'],
                'unique_together': {('country_code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('global_admin', 'Administrador Global'), ('country_admin', 'Administrador de País'), ('manager', 'Gerente'), ('user', 'Usuário')], default='user', max_length=20, verbose_name='Nível de Acesso')),
                ('country_code', models.CharField(blank=True, choices=[('BR', '🇧🇷 Brasil'), ('AR', '🇦🇷 Argentina'), ('MX', '🇲🇽 México'), ('DE', '🇩🇪 Alemanha'), ('IT', '🇮🇹 Itália'), ('CN', '🇨🇳 China'), ('US', '🇺🇸 Estados Unidos'), ('ES', '🇪🇸 Espanha'), ('FR', '🇫🇷 França'), ('GB', '🇬🇧 Reino Unido'), ('JP', '🇯🇵 Japão'), ('IN', '🇮🇳 Índia'), ('CA', '🇨🇦 Canadá'), ('AU', '🇦🇺 Austrália'), ('CL', '🇨🇱 Chile'), ('CO', '🇨🇴 Colômbia'), ('PE', '🇵🇪 Peru'), ('UY', '🇺🇾 Uruguai'), ('PY', '🇵🇾 Paraguai'), ('PT', '🇵🇹 Portugal'), ('NL', '🇳🇱 Holanda'), ('BE', '🇧🇪 Bélgica'), ('CH', '🇨🇭 Suíça'), ('AT', '🇦🇹 Áustria'), ('PL', '🇵🇱 Polônia'), ('CZ', '🇨🇿 República Tcheca'), ('RU', '🇷🇺 Rússia'), ('ZA', '🇿🇦 África do Sul'), ('EG', '🇪🇬 Egito'), ('KR', '🇰🇷 Coreia do Sul'), ('TH', '🇹🇭 Tailândia'), ('VN', '🇻🇳 Vietnã'), ('ID', '🇮🇩 Indonésia'), ('MY', '🇲🇾 Malásia'), ('SG', '🇸🇬 Singapura'), ('TR', '🇹🇷 Turquia'), ('SA', '🇸🇦 Arábia Saudita'), ('AE', '🇦🇪 Emirados Árabes')], max_length=5, null=True, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Administrador',
                'verbose_name_plural': 'Perfis de Administradores',
                'ordering': ['access_level', 'country_code', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='CountryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_configure_ad', models.BooleanField(default=False, verbose_name='Pode Configurar Active Directory')),
                ('ad_config_type', models.CharField(choices=[('own', 'Configuração Própria'), ('manual', 'Configuração Manual (definida pelo Global Admin)'), ('system_default', 'Usar Padrão do Sistema')], default='own', help_text='Se "Pode Configurar AD" = False, define qual configuração usar', max_length=20, verbose_name='Tipo de Configuração AD')),
                ('can_configure_smtp', models.BooleanField(default=False, verbose_name='Pode Configurar SMTP')),
                ('smtp_config_type', models.CharField(choices=[('own', 'Configuração Própria'), ('manual', 'Configuração Manual (definida pelo Global Admin)'), ('system_default', 'Usar Padrão do Sistema')], default='own', help_text='Se "Pode Configurar SMTP" = False, define qual configuração usar', max_length=20, verbose_name='Tipo de Configuração SMTP')),
                ('can_sync_ad_groups', models.BooleanField(default=True, verbose_name='Pode Sincronizar Grupos do AD')),
                ('can_assign_permissions', models.BooleanField(default=True, verbose_name='Pode Atribuir Permissões')),
                ('can_manage_local_users', models.BooleanField(default=True, verbose_name='Pode Gerenciar Usuários Locais')),
                ('can_manage_suppliers', models.BooleanField(default=True, verbose_name='Pode Gerenciar Fornecedores')),
                ('can_manage_contracts', models.BooleanField(default=True, verbose_name='Pode Gerenciar Contratos')),
                ('can_manage_quality', models.BooleanField(default=True, verbose_name='Pode Gerenciar Qualidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('admin_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='country_permissions', to='access_control.adminprofile', verbose_name='Perfil de Admin')),
            ],
            options={
                'verbose_name': 'Permissão de País',
                'verbose_name_plural': 'Permissões de Países',
            },
        ),
        migrations.CreateModel(
            name='SystemDefaultConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_enabled', models.BooleanField(default=False, help_text='Habilitar configuração AD padrão do sistema', verbose_name='AD Padrão Ativo')),
                ('ad_server', models.CharField(blank=True, help_text='Exemplo: ad.empresa.com', max_length=255, verbose_name='Servidor AD')),
                ('ad_port', models.IntegerField(default=389, verbose_name='Porta AD')),
                ('ad_use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL (LDAPS)')),
                ('ad_use_tls', models.BooleanField(default=False, verbose_name='Usar START_TLS')),
                ('ad_bind_user_dn', models.CharField(blank=True, help_text='Exemplo: CN=Admin,CN=Users,DC=empresa,DC=com', max_length=500, verbose_name='User DN para Bind')),
                ('ad_bind_password', models.CharField(blank=True, max_length=500, verbose_name='Senha do Bind (criptografada)')),
                ('ad_base_dn', models.CharField(blank=True, help_text='Exemplo: DC=empresa,DC=com', max_length=500, verbose_name='Base DN')),
                ('ad_user_search_base', models.CharField(blank=True, max_length=500, verbose_name='Base de Busca de Usuários')),
                ('ad_search_filter', models.CharField(blank=True, default='(sAMAccountName={username})', max_length=255, verbose_name='Filtro de Busca LDAP')),
                ('smtp_enabled', models.BooleanField(default=False, help_text='Habilitar configuração SMTP padrão do sistema', verbose_name='SMTP Padrão Ativo')),
                ('smtp_host', models.CharField(blank=True, help_text='Exemplo: smtp.gmail.com', max_length=255, verbose_name='Servidor SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Porta SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('smtp_username', models.CharField(blank=True, max_length=255, verbose_name='Usuário SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=500, verbose_name='Senha SMTP (criptografada)')),
                ('smtp_from_email', models.EmailField(blank=True, help_text='Email que aparecerá como remetente', max_length=254, verbose_name='Email Remetente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_configs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
            ],
            options={
                'verbose_name': 'Configuração Padrão do Sistema',
                'verbose_name_plural': 'Configurações Padrão do Sistema',
            },
        ),
        migrations.CreateModel(
            name='ADUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('BR', '🇧🇷 Brasil'), ('AR', '🇦🇷 Argentina'), ('MX', '🇲🇽 México'), ('DE', '🇩🇪 Alemanha'), ('IT', '🇮🇹 Itália'), ('CN', '🇨🇳 China'), ('US', '🇺🇸 Estados Unidos'), ('ES', '🇪🇸 Espanha'), ('FR', '🇫🇷 França'), ('GB', '🇬🇧 Reino Unido'), ('JP', '🇯🇵 Japão'), ('IN', '🇮🇳 Índia'), ('CA', '🇨🇦 Canadá'), ('AU', '🇦🇺 Austrália'), ('CL', '🇨🇱 Chile'), ('CO', '🇨🇴 Colômbia'), ('PE', '🇵🇪 Peru'), ('UY', '🇺🇾 Uruguai'), ('PY', '🇵🇾 Paraguai'), ('PT', '🇵🇹 Portugal'), ('NL', '🇳🇱 Holanda'), ('BE', '🇧🇪 Bélgica'), ('CH', '🇨🇭 Suíça'), ('AT', '🇦🇹 Áustria'), ('PL', '🇵🇱 Polônia'), ('CZ', '🇨🇿 República Tcheca'), ('RU', '🇷🇺 Rússia'), ('ZA', '🇿🇦 África do Sul'), ('EG', '🇪🇬 Egito'), ('KR', '🇰🇷 Coreia do Sul'), ('TH', '🇹🇭 Tailândia'), ('VN', '🇻🇳 Vietnã'), ('ID', '🇮🇩 Indonésia'), ('MY', '🇲🇾 Malásia'), ('SG', '🇸🇬 Singapura'), ('TR', '🇹🇷 Turquia'), ('SA', '🇸🇦 Arábia Saudita'), ('AE', '🇦🇪 Emirados Árabes')], max_length=2)),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('distinguished_name', models.CharField(default='', max_length=500, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=300)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('can_create_suppliers', models.BooleanField(default=False, verbose_name='Pode criar fornecedores')),
                ('can_edit_suppliers', models.BooleanField(default=False, verbose_name='Pode editar fornecedores')),
                ('can_delete_suppliers', models.BooleanField(default=False, verbose_name='Pode excluir fornecedores')),
                ('has_individual_permissions', models.BooleanField(default=False, verbose_name='Tem permissões individuais')),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='users', to='access_control.adgroup')),
            ],
            options={
                'verbose_name': 'Usuário do AD',
                'verbose_name_plural': 'Usuários do AD',
                'ordering': ['country_code', 'display_name'],
                'unique_together': {('country_code', 'username')},
            },
        ),
    ]
