# Generated by Django 5.0.7 on 2025-10-29 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('BR', '🇧🇷 Brasil'), ('AR', '🇦🇷 Argentina'), ('MX', '🇲🇽 México'), ('DE', '🇩🇪 Alemanha'), ('IT', '🇮🇹 Itália'), ('CN', '🇨🇳 China'), ('US', '🇺🇸 Estados Unidos')], max_length=5, verbose_name='País')),
                ('ad_group_name', models.CharField(max_length=200, verbose_name='Nome do Grupo no AD')),
                ('ad_group_dn', models.CharField(help_text='DN completo do grupo no AD', max_length=500, verbose_name='Distinguished Name (DN)')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('member_count', models.IntegerField(default=0, verbose_name='Quantidade de Membros')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_groups_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
            ],
            options={
                'verbose_name': 'Grupo do AD',
                'verbose_name_plural': 'Grupos do AD',
                'ordering': ['country_code', 'ad_group_name'],
                'unique_together': {('country_code', 'ad_group_dn')},
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('global_admin', 'Administrador Global'), ('country_admin', 'Administrador de País'), ('manager', 'Gerente'), ('user', 'Usuário')], default='user', max_length=20, verbose_name='Nível de Acesso')),
                ('country_code', models.CharField(blank=True, choices=[('BR', '🇧🇷 Brasil'), ('AR', '🇦🇷 Argentina'), ('MX', '🇲🇽 México'), ('DE', '🇩🇪 Alemanha'), ('IT', '🇮🇹 Itália'), ('CN', '🇨🇳 China'), ('US', '🇺🇸 Estados Unidos')], max_length=5, null=True, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Administrador',
                'verbose_name_plural': 'Perfis de Administradores',
                'ordering': ['access_level', 'country_code', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='CountryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_configure_ad', models.BooleanField(default=False, verbose_name='Pode Configurar Active Directory')),
                ('can_configure_smtp', models.BooleanField(default=False, verbose_name='Pode Configurar SMTP')),
                ('can_sync_ad_groups', models.BooleanField(default=True, verbose_name='Pode Sincronizar Grupos do AD')),
                ('can_assign_permissions', models.BooleanField(default=True, verbose_name='Pode Atribuir Permissões')),
                ('can_manage_local_users', models.BooleanField(default=True, verbose_name='Pode Gerenciar Usuários Locais')),
                ('can_manage_suppliers', models.BooleanField(default=True, verbose_name='Pode Gerenciar Fornecedores')),
                ('can_manage_contracts', models.BooleanField(default=True, verbose_name='Pode Gerenciar Contratos')),
                ('can_manage_quality', models.BooleanField(default=True, verbose_name='Pode Gerenciar Qualidade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('admin_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='country_permissions', to='access_control.adminprofile', verbose_name='Perfil de Admin')),
            ],
            options={
                'verbose_name': 'Permissão de País',
                'verbose_name_plural': 'Permissões de Países',
            },
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(choices=[('view_suppliers', 'Visualizar Fornecedores'), ('create_suppliers', 'Criar Fornecedores'), ('edit_suppliers', 'Editar Fornecedores'), ('delete_suppliers', 'Excluir Fornecedores'), ('view_contracts', 'Visualizar Contratos'), ('create_contracts', 'Criar Contratos'), ('edit_contracts', 'Editar Contratos'), ('delete_contracts', 'Excluir Contratos'), ('view_quality', 'Visualizar Qualidade'), ('manage_quality', 'Gerenciar Qualidade'), ('view_reports', 'Visualizar Relatórios'), ('export_reports', 'Exportar Relatórios'), ('manage_users', 'Gerenciar Usuários'), ('manage_settings', 'Gerenciar Configurações')], max_length=50, verbose_name='Permissão')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Concedida Em')),
                ('ad_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access_control.adgroup', verbose_name='Grupo do AD')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Concedida Por')),
            ],
            options={
                'verbose_name': 'Permissão de Grupo',
                'verbose_name_plural': 'Permissões de Grupos',
                'ordering': ['ad_group', 'permission_code'],
                'unique_together': {('ad_group', 'permission_code')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(choices=[('view_suppliers', 'Visualizar Fornecedores'), ('create_suppliers', 'Criar Fornecedores'), ('edit_suppliers', 'Editar Fornecedores'), ('delete_suppliers', 'Excluir Fornecedores'), ('view_contracts', 'Visualizar Contratos'), ('create_contracts', 'Criar Contratos'), ('edit_contracts', 'Editar Contratos'), ('delete_contracts', 'Excluir Contratos'), ('view_quality', 'Visualizar Qualidade'), ('manage_quality', 'Gerenciar Qualidade'), ('view_reports', 'Visualizar Relatórios'), ('export_reports', 'Exportar Relatórios'), ('manage_users', 'Gerenciar Usuários'), ('manage_settings', 'Gerenciar Configurações')], max_length=50, verbose_name='Permissão')),
                ('is_granted', models.BooleanField(default=True, help_text='True = Conceder, False = Revogar (mesmo que o grupo tenha)', verbose_name='Concedida')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Modificada Em')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Modificada Por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de Usuário',
                'verbose_name_plural': 'Permissões de Usuários',
                'ordering': ['user', 'permission_code'],
                'unique_together': {('user', 'permission_code')},
            },
        ),
    ]
