# Generated by Django 5.0.7 on 2025-10-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adgroup',
            name='country_code',
            field=models.CharField(choices=[('BR', '🇧🇷 Brasil'), ('AR', '🇦🇷 Argentina'), ('MX', '🇲🇽 México'), ('DE', '🇩🇪 Alemanha'), ('IT', '🇮🇹 Itália'), ('CN', '🇨🇳 China'), ('US', '🇺🇸 Estados Unidos'), ('ES', '🇪🇸 Espanha'), ('FR', '🇫🇷 França'), ('GB', '🇬🇧 Reino Unido'), ('JP', '🇯🇵 Japão'), ('IN', '🇮🇳 Índia'), ('CA', '🇨🇦 Canadá'), ('AU', '🇦🇺 Austrália'), ('CL', '🇨🇱 Chile'), ('CO', '🇨🇴 Colômbia'), ('PE', '🇵🇪 Peru'), ('UY', '🇺🇾 Uruguai'), ('PY', '🇵🇾 Paraguai'), ('PT', '🇵🇹 Portugal'), ('NL', '🇳🇱 Holanda'), ('BE', '🇧🇪 Bélgica'), ('CH', '🇨🇭 Suíça'), ('AT', '🇦🇹 Áustria'), ('PL', '🇵🇱 Polônia'), ('CZ', '🇨🇿 República Tcheca'), ('RU', '🇷🇺 Rússia'), ('ZA', '🇿🇦 África do Sul'), ('EG', '🇪🇬 Egito'), ('KR', '🇰🇷 Coreia do Sul'), ('TH', '🇹🇭 Tailândia'), ('VN', '🇻🇳 Vietnã'), ('ID', '🇮🇩 Indonésia'), ('MY', '🇲🇾 Malásia'), ('SG', '🇸🇬 Singapura'), ('TR', '🇹🇷 Turquia'), ('SA', '🇸🇦 Arábia Saudita'), ('AE', '🇦🇪 Emirados Árabes')], max_length=5, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='country_code',
            field=models.CharField(blank=True, choices=[('BR', '🇧🇷 Brasil'), ('AR', '🇦🇷 Argentina'), ('MX', '🇲🇽 México'), ('DE', '🇩🇪 Alemanha'), ('IT', '🇮🇹 Itália'), ('CN', '🇨🇳 China'), ('US', '🇺🇸 Estados Unidos'), ('ES', '🇪🇸 Espanha'), ('FR', '🇫🇷 França'), ('GB', '🇬🇧 Reino Unido'), ('JP', '🇯🇵 Japão'), ('IN', '🇮🇳 Índia'), ('CA', '🇨🇦 Canadá'), ('AU', '🇦🇺 Austrália'), ('CL', '🇨🇱 Chile'), ('CO', '🇨🇴 Colômbia'), ('PE', '🇵🇪 Peru'), ('UY', '🇺🇾 Uruguai'), ('PY', '🇵🇾 Paraguai'), ('PT', '🇵🇹 Portugal'), ('NL', '🇳🇱 Holanda'), ('BE', '🇧🇪 Bélgica'), ('CH', '🇨🇭 Suíça'), ('AT', '🇦🇹 Áustria'), ('PL', '🇵🇱 Polônia'), ('CZ', '🇨🇿 República Tcheca'), ('RU', '🇷🇺 Rússia'), ('ZA', '🇿🇦 África do Sul'), ('EG', '🇪🇬 Egito'), ('KR', '🇰🇷 Coreia do Sul'), ('TH', '🇹🇭 Tailândia'), ('VN', '🇻🇳 Vietnã'), ('ID', '🇮🇩 Indonésia'), ('MY', '🇲🇾 Malásia'), ('SG', '🇸🇬 Singapura'), ('TR', '🇹🇷 Turquia'), ('SA', '🇸🇦 Arábia Saudita'), ('AE', '🇦🇪 Emirados Árabes')], max_length=5, null=True, verbose_name='País'),
        ),
    ]
