# Generated by Django 5.0.7 on 2025-11-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adgroup',
            name='can_create_suppliers',
        ),
        migrations.RemoveField(
            model_name='adgroup',
            name='can_delete_suppliers',
        ),
        migrations.RemoveField(
            model_name='adgroup',
            name='can_edit_suppliers',
        ),
        migrations.RemoveField(
            model_name='aduser',
            name='can_create_suppliers',
        ),
        migrations.RemoveField(
            model_name='aduser',
            name='can_delete_suppliers',
        ),
        migrations.RemoveField(
            model_name='aduser',
            name='can_edit_suppliers',
        ),
        migrations.AddField(
            model_name='adgroup',
            name='can_handle_complaints',
            field=models.BooleanField(default=False, verbose_name='Pode Tratar Reclamações'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='can_login',
            field=models.BooleanField(default=False, verbose_name='Pode Fazer Login'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='can_manage_contracts',
            field=models.BooleanField(default=False, verbose_name='Pode Gerenciar Contratos'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='can_register_suppliers',
            field=models.BooleanField(default=False, verbose_name='Pode Cadastrar Fornecedores'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='can_view_contracts',
            field=models.BooleanField(default=False, verbose_name='Pode Visualizar Contratos'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='can_view_dashboards',
            field=models.BooleanField(default=False, verbose_name='Pode Visualizar Dashboards'),
        ),
        migrations.AddField(
            model_name='aduser',
            name='can_handle_complaints',
            field=models.BooleanField(default=False, verbose_name='Pode Tratar Reclamações'),
        ),
        migrations.AddField(
            model_name='aduser',
            name='can_login',
            field=models.BooleanField(default=False, verbose_name='Pode Fazer Login'),
        ),
        migrations.AddField(
            model_name='aduser',
            name='can_manage_contracts',
            field=models.BooleanField(default=False, verbose_name='Pode Gerenciar Contratos'),
        ),
        migrations.AddField(
            model_name='aduser',
            name='can_register_suppliers',
            field=models.BooleanField(default=False, verbose_name='Pode Cadastrar Fornecedores'),
        ),
        migrations.AddField(
            model_name='aduser',
            name='can_view_contracts',
            field=models.BooleanField(default=False, verbose_name='Pode Visualizar Contratos'),
        ),
        migrations.AddField(
            model_name='aduser',
            name='can_view_dashboards',
            field=models.BooleanField(default=False, verbose_name='Pode Visualizar Dashboards'),
        ),
    ]
