# Generated by Django 5.0.7 on 2025-10-30 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_adgroup_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypermission',
            name='ad_config_type',
            field=models.CharField(choices=[('own', 'Configuração Própria'), ('manual', 'Configuração Manual (definida pelo Global Admin)'), ('system_default', 'Usar Padrão do Sistema')], default='own', help_text='Se "Pode Configurar AD" = False, define qual configuração usar', max_length=20, verbose_name='Tipo de Configuração AD'),
        ),
        migrations.AddField(
            model_name='countrypermission',
            name='smtp_config_type',
            field=models.CharField(choices=[('own', 'Configuração Própria'), ('manual', 'Configuração Manual (definida pelo Global Admin)'), ('system_default', 'Usar Padrão do Sistema')], default='own', help_text='Se "Pode Configurar SMTP" = False, define qual configuração usar', max_length=20, verbose_name='Tipo de Configuração SMTP'),
        ),
        migrations.CreateModel(
            name='SystemDefaultConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_enabled', models.BooleanField(default=False, help_text='Habilitar configuração AD padrão do sistema', verbose_name='AD Padrão Ativo')),
                ('ad_server', models.CharField(blank=True, help_text='Exemplo: ad.empresa.com', max_length=255, verbose_name='Servidor AD')),
                ('ad_port', models.IntegerField(default=389, verbose_name='Porta AD')),
                ('ad_use_ssl', models.BooleanField(default=False, verbose_name='Usar SSL (LDAPS)')),
                ('ad_use_tls', models.BooleanField(default=False, verbose_name='Usar START_TLS')),
                ('ad_bind_user_dn', models.CharField(blank=True, help_text='Exemplo: CN=Admin,CN=Users,DC=empresa,DC=com', max_length=500, verbose_name='User DN para Bind')),
                ('ad_bind_password', models.CharField(blank=True, max_length=500, verbose_name='Senha do Bind (criptografada)')),
                ('ad_base_dn', models.CharField(blank=True, help_text='Exemplo: DC=empresa,DC=com', max_length=500, verbose_name='Base DN')),
                ('ad_user_search_base', models.CharField(blank=True, max_length=500, verbose_name='Base de Busca de Usuários')),
                ('ad_search_filter', models.CharField(blank=True, default='(sAMAccountName={username})', max_length=255, verbose_name='Filtro de Busca LDAP')),
                ('smtp_enabled', models.BooleanField(default=False, help_text='Habilitar configuração SMTP padrão do sistema', verbose_name='SMTP Padrão Ativo')),
                ('smtp_host', models.CharField(blank=True, help_text='Exemplo: smtp.gmail.com', max_length=255, verbose_name='Servidor SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Porta SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('smtp_username', models.CharField(blank=True, max_length=255, verbose_name='Usuário SMTP')),
                ('smtp_password', models.CharField(blank=True, max_length=500, verbose_name='Senha SMTP (criptografada)')),
                ('smtp_from_email', models.EmailField(blank=True, help_text='Email que aparecerá como remetente', max_length=254, verbose_name='Email Remetente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_configs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado Por')),
            ],
            options={
                'verbose_name': 'Configuração Padrão do Sistema',
                'verbose_name_plural': 'Configurações Padrão do Sistema',
            },
        ),
    ]
